### ISSUE TITLE
Utilize Github Path for Gobrake Library

### ISSUE THREAD

**Issue by jonmchan** [gemnasium/logrus-airbrake-hook#3]
Gobrake v3 was released a few months ago. I would like to upgrade to the latest version of gobrake, but having problems with imports being compatible:

```
# github.com/mycompany/mypproject/libs
libs/initializer.go:46: cannot use func literal (type func(*"github.com/mycompany/mypproject/vendor/github.com/airbrake/gobrake".Notice) *"github.com/mycompany/mypproject/vendor/github.com/airbrake/gobrake".Notice) as type "github.com/mycompany/mypproject/vendor/gopkg.in/airbrake/gobrake.v2".filter in argument to hook.Airbrake.AddFilter
```

For logrus, we aren't using gopkg (```"github.com/sirupsen/logrus"```), could we do the same for gobrake? I use glide to manage my dependencies and find it easier to lock versions down using a glide.lock/glide.yml than having to change all my imports every time a new version comes out.

**Comment by gravis** [comment]
We can't change the import path without breaking changes for existing users.
On the other hand, I can create a v3 branch to support gobrake v3

**Comment by gravis** [comment]
After go 1.9 is released, and godep available widely, we could have a master branch without gopkg.in btw

**Comment by jonmchan** [comment]
That is very true about breaking changes for existing users. Then again, what's 1 more breaking change after sirupsen's casing breaking change? ;-) Totally just kidding. I'll appreciate a v3 version.

**Comment by gravis** [comment]
@jonmchan logrus-airbrake-hook is now using gobrake-v3.
Can't wait for go 1.9 with an official dep manager...
