### ISSUE TITLE
New Trace logrus level

### ISSUE THREAD

**Issue by dgsb** [gemnasium/logrus-airbrake-hook#4]
Hello, I'm just opening this issue to let you know, the next release of logrus (v1.2.0) will add a new trace level named Trace below Debug.
Here is the PR for reference sirupsen/logrus#844
You may/want to take into account this new level.

**Comment by gravis** [comment]
Similar to https://github.com/gemnasium/logrus-airbrake-legacy-hook/issues/2:

> As it has no knowledge of WarnLevel, InfoLevel or DebugLevel, I doubt it would care to know about TraceLevel for any reason.
