### ISSUE TITLE
Error hook.Airbrake.Client undefined

### ISSUE THREAD

**Issue by fbsyn** [gemnasium/logrus-airbrake-hook#5]
Hi,

When I test your project, I have this error :
`./airbrake_test.go:170:15: hook.Airbrake.Client undefined (type *gobrake.Notifier has no field or method Client)`

So, could you fix this problem ? hook.Airbrake.Client is available in Version 2 of github.com/airbrake/gobrake and not in Version 3

Thanks

**Comment by gravis** [comment]
Thanks for pointing this. It's not fixed, by locking gobrake to v2. 
I'd like to support gobrake v3 in the future, but only when they'll support go modules.
