### ISSUE TITLE
Can you support gobrake version 5?

### ISSUE THREAD

**Issue by taross-f** [gemnasium/logrus-airbrake-hook#9]
Gobrake latest version is v5.5.2.
I am seeing a Warning within the Airbrake dashboard, which I would like to have supported!

Thanks.

https://github.com/airbrake/gobrake/releases/tag/v5.5.2
<img width="1140" alt="スクリーンショット 2022-08-19 14 37 58" src="https://user-images.githubusercontent.com/1595823/185550639-a05f7ae1-6c71-440c-85c0-5951ccd431fd.png">

**Comment by gravis** [comment]
@taross-f you can use the [v5.0.0](https://github.com/gemnasium/logrus-airbrake-hook/releases/tag/v5.0.0) tag from now on.
